Repository yalesites-org/ai_engine, pull requests merged in 2024-06, with the labels that each got.

#8 YSP-539: Bypass field_metatags if they don't exist
  modules/ai_engine_feed/ai_engine_feed.services.yml
  modules/ai_engine_feed/src/ApiLinkBuilderTrait.php
  modules/ai_engine_feed/src/Service/Sources.php
Labels: pass code review, pass functional review, ready to merge

#10 fix(YSP-539): be explicit about increment
  modules/ai_engine_feed/src/ApiLinkBuilderTrait.php
Labels: pass code review, pass functional review

#6 YSP-522: Separate permissions for admin and content settings
  ai_engine.permissions.yml
  modules/ai_engine_chat/ai_engine_chat.links.menu.yml
  modules/ai_engine_chat/ai_engine_chat.routing.yml
  modules/ai_engine_chat/src/Form/AiEngineChatAdmin.php
  modules/ai_engine_chat/src/Form/AiEngineChatSettings.php
  modules/ai_engine_embedding/ai_engine_embedding.links.menu.yml
Labels: pass code review, pass functional review, ready to merge

#7 YSP-523: Allow AI metadata fields to be hidden
  modules/ai_engine_metadata/ai_engine_metadata.links.menu.yml
  modules/ai_engine_metadata/ai_engine_metadata.module
  modules/ai_engine_metadata/ai_engine_metadata.routing.yml
  modules/ai_engine_metadata/config/install/ai_engine_metadata.settings.yml
  modules/ai_engine_metadata/src/Form/AiEngineMetadataAdmin.php
Labels: pass code review, pass functional review, ready to merge

#9 YSP-539: Feed metatag settings
  modules/ai_engine_feed/ai_engine_feed.links.menu.yml
  modules/ai_engine_feed/ai_engine_feed.routing.yml
  modules/ai_engine_feed/ai_engine_feed.services.yml
  modules/ai_engine_feed/src/Form/AiEngineFeedSettings.php
  modules/ai_engine_feed/src/Service/Sources.php
Labels: pass code review, ready to merge
